- id: '1637863362765'
  alias: Start Sunrise Simulation
  description: ''
  trigger:
  - platform: time
    at: 04:30:00
  condition: []
  action:
  - service: script.sunrise_simulation
  mode: single
